### ISSUE TITLE
missing dependency - Sereal

### ISSUE THREAD

**Issue by vytas-dauksa** [p5pclub/devel-quickcover#10]
Please add Sereal to dependency list

Thanks,
Vytas

**Comment by xsawyerx** [comment]
Fixed in 2a290db773336142f8bc6f332b802ea2c0f9d524. Awaiting next release.

**Comment by gonzus** [comment]
Just uploaded version 0.700000 to Pause. Thanks Vytas and Sawyer for all 
the patches!
